# fly.toml app configuration file generated for devils-dictionary on 2025-01-07T14:26:22-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'devils-dictionary'
primary_region = 'dfw'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[deploy]
  release_command = "bin/rails db:migrate"
  strategy = "immediate"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
